### ISSUE TITLE
[Request] Allow preview of currently worked on features through another GH branch.

### ISSUE THREAD

**Issue by Xtreme533** [emd4600/Spore-ModAPI#29]
With any currently unavailable features through the master branch, I'd like to see a preview of them in a different branch than master, to anticipate on what is going to be added next and such, even if the features aren't fully functional yet.

**Comment by emd4600** [comment]
The master branch is already the most updated one, having features that are currently not supported in the public DLLs used by the Spore ModAPI Launcher. Generally I don't use branches for this project because most features can be atomized in very small commits ("changed this structure", "added this method", ...), so any features being worked on are already in the master branch.

**Comment by Xtreme533** [comment]
Fair enough.
